"""CSV export for reports.

CSV uses only the Python standard library, so it always works even when the
optional PDF/Excel dependencies are missing.  A single CSV bundles the report
sections with clear section headers.
"""

from __future__ import annotations

import csv
from pathlib import Path
from typing import TYPE_CHECKING

from utils.helpers import format_timestamp

if TYPE_CHECKING:
    from reports.report_generator import ReportData


def export_csv(data: "ReportData", path: Path) -> Path:
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)

        writer.writerow([data.title])
        writer.writerow(["Report Type", data.report_type])
        writer.writerow(["Generated By", data.generated_by])
        writer.writerow(["Generated At", format_timestamp(data.generated_at)])
        writer.writerow(["Period",
                         f"{format_timestamp(data.period_start)} "
                         f"to {format_timestamp(data.period_end)}"])
        writer.writerow([])

        writer.writerow(["EXECUTIVE SUMMARY"])
        for key, value in data.summary.items():
            writer.writerow([key.replace("_", " ").title(), value])
        writer.writerow([])

        _section(writer, "DETECTED VULNERABILITIES",
                 ["Host", "Hostname", "Port", "Protocol", "Service", "Version",
                  "State", "Risk"],
                 [[v.get("host"), v.get("hostname"), v.get("port"),
                   v.get("protocol"), v.get("service"), v.get("version"),
                   v.get("state"), v.get("risk_level")] for v in data.vulnerabilities])

        _section(writer, "INTRUSION ALERTS",
                 ["Time", "Category", "Severity", "Source", "Destination",
                  "Protocol", "Occurrences", "Status"],
                 [[format_timestamp(a.get("timestamp")), a.get("category"),
                   a.get("severity"), a.get("source_ip"), a.get("destination_ip"),
                   a.get("protocol"), a.get("occurrences"), a.get("status")]
                  for a in data.alerts])

        _section(writer, "THREAT DISTRIBUTION", ["Threat", "Count"],
                 [[k, v] for k, v in data.threat_distribution.items()])

        _section(writer, "TOP DEVICES", ["IP", "Hostname", "Risk", "Total Packets"],
                 [[d.get("ip_address"), d.get("hostname"), d.get("risk_level"),
                   d.get("total_packets")] for d in data.top_devices])

        _section(writer, "MITIGATION RECOMMENDATIONS",
                 ["Threat", "Severity", "Title", "Recommendation"],
                 [[r.get("alert_type"), r.get("severity"),
                   r.get("recommendation_title"), r.get("recommendation")]
                  for r in data.recommendations])

        writer.writerow(["CONCLUSION"])
        writer.writerow([data.conclusion])
    return path


def _section(writer, title, header, rows) -> None:
    writer.writerow([title])
    writer.writerow(header)
    if not rows:
        writer.writerow(["(none)"])
    for row in rows:
        writer.writerow(row)
    writer.writerow([])
