"""Excel (.xlsx) export using openpyxl.

Each report section becomes its own worksheet so tabular data stays clean for
further analysis.  If openpyxl is unavailable a clear RuntimeError is raised so
the GUI can fall back to CSV.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from utils.helpers import format_timestamp

if TYPE_CHECKING:
    from reports.report_generator import ReportData

try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill
    _OPENPYXL_AVAILABLE = True
except Exception:  # pragma: no cover
    Workbook = None  # type: ignore
    _OPENPYXL_AVAILABLE = False


_HEADER_FILL = "1F3A5F"


def export_excel(data: "ReportData", path: Path) -> Path:
    if not _OPENPYXL_AVAILABLE:
        raise RuntimeError("openpyxl is not installed; cannot export Excel.")

    wb = Workbook()

    # Summary sheet.
    ws = wb.active
    ws.title = "Summary"
    ws.append([data.title])
    ws["A1"].font = Font(size=14, bold=True)
    ws.append(["Report Type", data.report_type])
    ws.append(["Generated By", data.generated_by])
    ws.append(["Generated At", format_timestamp(data.generated_at)])
    ws.append(["Period", f"{format_timestamp(data.period_start)} to "
                         f"{format_timestamp(data.period_end)}"])
    ws.append([])
    ws.append(["Metric", "Value"])
    _style_header(ws, ws.max_row)
    for key, value in data.summary.items():
        ws.append([key.replace("_", " ").title(), value])

    _add_sheet(wb, "Vulnerabilities",
               ["Host", "Hostname", "Port", "Protocol", "Service", "Version",
                "State", "Risk"],
               [[v.get("host"), v.get("hostname"), v.get("port"), v.get("protocol"),
                 v.get("service"), v.get("version"), v.get("state"),
                 v.get("risk_level")] for v in data.vulnerabilities])

    _add_sheet(wb, "Alerts",
               ["Time", "Category", "Severity", "Source", "Destination",
                "Protocol", "Occurrences", "Status"],
               [[format_timestamp(a.get("timestamp")), a.get("category"),
                 a.get("severity"), a.get("source_ip"), a.get("destination_ip"),
                 a.get("protocol"), a.get("occurrences"), a.get("status")]
                for a in data.alerts])

    _add_sheet(wb, "Devices",
               ["IP", "Hostname", "MAC", "OS", "Risk", "Status", "Sent", "Received"],
               [[d.get("ip_address"), d.get("hostname"), d.get("mac_address"),
                 d.get("operating_system"), d.get("risk_level"), d.get("status"),
                 d.get("packets_sent"), d.get("packets_received")]
                for d in data.devices])

    _add_sheet(wb, "Threat Distribution", ["Threat", "Count"],
               [[k, v] for k, v in data.threat_distribution.items()])

    _add_sheet(wb, "Recommendations",
               ["Threat", "Severity", "Title", "Recommendation"],
               [[r.get("alert_type"), r.get("severity"),
                 r.get("recommendation_title"), r.get("recommendation")]
                for r in data.recommendations])

    wb.save(path)
    return path


def _add_sheet(wb, title, header, rows) -> None:
    ws = wb.create_sheet(title=title[:31])
    ws.append(header)
    _style_header(ws, 1)
    if not rows:
        ws.append(["(none)"])
    for row in rows:
        ws.append(row)
    _autosize(ws, len(header))


def _style_header(ws, row_idx: int) -> None:
    for cell in ws[row_idx]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=_HEADER_FILL)


def _autosize(ws, columns: int) -> None:
    for col in range(1, columns + 1):
        letter = ws.cell(row=1, column=col).column_letter
        width = 12
        for cell in ws[letter]:
            if cell.value is not None:
                width = max(width, min(50, len(str(cell.value)) + 2))
        ws.column_dimensions[letter].width = width
