"""PDF report export using ReportLab, with embedded Matplotlib charts.

Produces a professional multi-section report: cover page, executive summary,
vulnerabilities, alerts, threat distribution chart, top devices, mitigation
recommendations, and conclusion.  Charts are rendered off-screen with the
Matplotlib ``Agg`` backend so no GUI is required.

If ReportLab is unavailable a clear RuntimeError is raised so the GUI can fall
back to CSV.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List

from config import APP_NAME, APP_VERSION, CONFIG
from utils.constants import SEVERITY_COLORS
from utils.helpers import format_timestamp

if TYPE_CHECKING:
    from reports.report_generator import ReportData

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak,
    )
    _REPORTLAB_AVAILABLE = True
except Exception:  # pragma: no cover
    _REPORTLAB_AVAILABLE = False

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    _MPL_AVAILABLE = True
except Exception:  # pragma: no cover
    _MPL_AVAILABLE = False


def export_pdf(data: "ReportData", path: Path) -> Path:
    if not _REPORTLAB_AVAILABLE:
        raise RuntimeError("reportlab is not installed; cannot export PDF.")

    doc = SimpleDocTemplate(str(path), pagesize=A4,
                            topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="AethraTitle", fontSize=24, leading=28,
                              textColor=colors.HexColor("#1F3A5F"), spaceAfter=12))
    styles.add(ParagraphStyle(name="Section", fontSize=14, leading=18,
                              textColor=colors.HexColor("#1F3A5F"), spaceBefore=14,
                              spaceAfter=6))
    story: List = []

    _cover(story, styles, data)
    story.append(PageBreak())
    _summary(story, styles, data)
    _chart_section(story, styles, data)
    _vulnerability_section(story, styles, data)
    _alert_section(story, styles, data)
    _device_section(story, styles, data)
    _recommendation_section(story, styles, data)
    _conclusion(story, styles, data)

    doc.build(story)
    return path


def _cover(story, styles, data: "ReportData") -> None:
    story.append(Spacer(1, 4 * cm))
    story.append(Paragraph(APP_NAME, styles["AethraTitle"]))
    story.append(Paragraph(
        "Unified Cybersecurity Monitoring &amp; Assessment Platform",
        styles["Heading3"]))
    story.append(Spacer(1, 1 * cm))
    story.append(Paragraph(data.report_type, styles["Heading1"]))
    story.append(Spacer(1, 1 * cm))
    meta = [
        ["Generated By", data.generated_by],
        ["Generated At", format_timestamp(data.generated_at)],
        ["Reporting Period",
         f"{format_timestamp(data.period_start)}  to  {format_timestamp(data.period_end)}"],
        ["Organization", CONFIG.reports.organization_name],
        ["Laboratory", CONFIG.reports.laboratory_name],
        ["Version", f"{APP_NAME} v{APP_VERSION}"],
    ]
    table = Table(meta, colWidths=[5 * cm, 10 * cm])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#1F3A5F")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(table)


def _summary(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Executive Summary", styles["Section"]))
    rows = [["Metric", "Value"]]
    for key, value in data.summary.items():
        rows.append([key.replace("_", " ").title(), str(value)])
    table = Table(rows, colWidths=[9 * cm, 6 * cm])
    table.setStyle(_grid_style())
    story.append(table)


def _chart_section(story, styles, data: "ReportData") -> None:
    if not _MPL_AVAILABLE:
        return
    if data.threat_distribution:
        img = _bar_chart(data.threat_distribution, "Threat Distribution")
        if img:
            story.append(Paragraph("Threat Distribution", styles["Section"]))
            story.append(img)
    if data.severity_distribution:
        img = _severity_chart(data.severity_distribution)
        if img:
            story.append(Paragraph("Alert Severity", styles["Section"]))
            story.append(img)


def _vulnerability_section(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Detected Vulnerabilities", styles["Section"]))
    if not data.vulnerabilities:
        story.append(Paragraph("No open services detected in this period.",
                               styles["Normal"]))
        return
    rows = [["Host", "Port", "Service", "Version", "Risk"]]
    for v in data.vulnerabilities[:40]:
        rows.append([v.get("host", ""), str(v.get("port", "")),
                     v.get("service", ""), (v.get("version") or "")[:24],
                     v.get("risk_level", "")])
    table = Table(rows, colWidths=[3.5 * cm, 1.6 * cm, 3 * cm, 4 * cm, 2.9 * cm])
    table.setStyle(_grid_style())
    story.append(table)


def _alert_section(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Intrusion Alerts", styles["Section"]))
    if not data.alerts:
        story.append(Paragraph("No intrusion alerts recorded in this period.",
                               styles["Normal"]))
        return
    rows = [["Time", "Category", "Severity", "Source", "Dest", "Occ."]]
    for a in data.alerts[:40]:
        rows.append([format_timestamp(a.get("timestamp"), "%m-%d %H:%M"),
                     a.get("category", ""), a.get("severity", ""),
                     a.get("source_ip", ""), a.get("destination_ip", ""),
                     str(a.get("occurrences", ""))])
    table = Table(rows, colWidths=[2.6 * cm, 3.2 * cm, 2.2 * cm, 3 * cm, 3 * cm, 1.5 * cm])
    table.setStyle(_grid_style())
    story.append(table)


def _device_section(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Top Devices", styles["Section"]))
    if not data.top_devices:
        story.append(Paragraph("No devices observed.", styles["Normal"]))
        return
    rows = [["IP Address", "Hostname", "Risk", "Packets"]]
    for d in data.top_devices:
        rows.append([d.get("ip_address", ""), (d.get("hostname") or "")[:24],
                     d.get("risk_level", ""), str(d.get("total_packets", 0))])
    table = Table(rows, colWidths=[4 * cm, 5 * cm, 3 * cm, 3 * cm])
    table.setStyle(_grid_style())
    story.append(table)


def _recommendation_section(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Mitigation Recommendations", styles["Section"]))
    if not data.recommendations:
        story.append(Paragraph("No recommendations applicable.", styles["Normal"]))
        return
    for rec in data.recommendations[:10]:
        story.append(Paragraph(
            f"<b>{rec.get('recommendation_title', '')}</b> "
            f"({rec.get('severity', '')})", styles["Normal"]))
        story.append(Paragraph(rec.get("recommendation", ""), styles["Normal"]))
        story.append(Spacer(1, 0.3 * cm))


def _conclusion(story, styles, data: "ReportData") -> None:
    story.append(Paragraph("Conclusion", styles["Section"]))
    story.append(Paragraph(data.conclusion, styles["Normal"]))


# ---------------------------------------------------------------- chart helpers
def _bar_chart(dist: Dict[str, int], title: str):
    try:
        fig, ax = plt.subplots(figsize=(6, 3))
        labels = list(dist.keys())[:8]
        values = [dist[k] for k in labels]
        ax.barh(labels, values, color="#1F3A5F")
        ax.set_title(title)
        ax.invert_yaxis()
        fig.tight_layout()
        return _fig_to_image(fig)
    except Exception:  # noqa: BLE001
        return None


def _severity_chart(dist: Dict[str, int]):
    try:
        order = ["Critical", "High", "Medium", "Low", "Informational"]
        labels = [s for s in order if s in dist]
        values = [dist[s] for s in labels]
        cols = [SEVERITY_COLORS.get(s, "#888888") for s in labels]
        fig, ax = plt.subplots(figsize=(6, 3))
        ax.bar(labels, values, color=cols)
        ax.set_title("Alerts by Severity")
        fig.tight_layout()
        return _fig_to_image(fig)
    except Exception:  # noqa: BLE001
        return None


def _fig_to_image(fig):
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=110)
    plt.close(fig)
    buf.seek(0)
    return Image(buf, width=15 * cm, height=7.5 * cm)


def _grid_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3A5F")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#cccccc")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.white, colors.HexColor("#f2f5f9")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("PADDING", (0, 0), (-1, -1), 4),
    ])
